language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-newrelic.gemspec
- gem install sensu-plugins-newrelic-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: ZkfALW0QaNmrzo614XgbB1VRldqL5rImTBRBV26iWwxcQ4RQozW3SL36Wz5N9E4S6EsUqds44ePgvFoNfxYVSLTD/AzpdiVkdsw+Tj46LnBa2LOk4IFf/QEWjkDO9CFXRAhq7UOe2aFPaOmTuQv6gn+krzt60Cs+izOaqT2E9lc=
  gem: sensu-plugins-newrelic
  on:
    tags: true
    repo: sensu-plugins/sensu-plugins-newrelic
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
